apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongodb
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  volumes:
    - name: mongo-persistent-storage
      persistentVolumeClaim:
        claimName: mongo-persistent-storage-mongo
  containers:
    - name: mongodb
      image: mongo
      ports:
        - containerPort: 27017
          name: "http-server"
      volumeMounts:
        - mountPath: "/data/db"
          name: mongo-persistent-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/medicalApp-master/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-storage-mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
