apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: medicalapp
  name: medicalapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: medicalapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: medicalapp
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: assemammar/medicalapp_2021:latest
        imagePullPolicy: "Always"
        name: medicalapp
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: medicalapp
  labels:
    run: medicalapp
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: medicalapp
